from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class Vector(BaseModel):
    """Schema for a vector embedding"""
    vector: List[float] = Field(..., description="The vector embedding")

class Topic(BaseModel):
    """Schema for a topic with name and description"""
    name: str = Field(..., description="Topic name (e.g., 'embedded banking APIs for banks')")
    description: str = Field(..., description="Topic description explaining the concept")

class MarketTopics(BaseModel):
    """Schema for market topics generated by AI"""
    topics: List[Topic] = Field(..., description="List of ~15 topics for the market")

class VectorEmbedding(BaseModel):
    """Stored vector embedding linked to a market"""
    id: int = Field(..., description="Database ID")
    market_id: int = Field(..., description="Reference to market")
    embedding: List[float] = Field(..., description="Vector embedding")
    topics: Optional[List[dict]] = Field(None, description="AI-generated topics for the market")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Update timestamp")
    
    class Config:
        from_attributes = True

class VectorEmbeddingCreate(BaseModel):
    """Schema for creating a vector embedding"""
    market_id: int = Field(..., description="Market ID to create embedding for")

class Dataset(BaseModel):
    """Dataset with market and its embedding"""
    market_id: int
    embedding: List[float]

class SimilarityResult(BaseModel):
    """Result from similarity search"""
    market_id: int
    similarity: float

class SimilaritySearchResponse(BaseModel):
    """Response for similarity searches"""
    results: List[SimilarityResult]
    count: int
